### ISSUE TITLE
consideration: rename command line interface 

### ISSUE THREAD

**Issue by akileez** [jonschlinkert/module-tree#4]
if I install this globally, it will overwrite the unix package `tree`. 
perhaps call the cli: dtree?

what do you think?

**Comment by jonschlinkert** [comment]
lol yikes, I meant to name it `module-tree`, but I had a temporary name in the package for a bit b/c I couldn't think of a name. would that work for you? I can change unless you'd like to do a pr

**Comment by akileez** [comment]
honestly, I don't care what the name is... as long as it's not `tree`

**Comment by akileez** [comment]
i was only thinking `dtree` for dependency-tree, `mtree` for module-tree. anything. when on the command line, I like short. but in this case anything will do. no preference here.

**Comment by jonschlinkert** [comment]
`mtree` sounds good. want to do a pr?

**Comment by akileez** [comment]
sure.

**Comment by jonschlinkert** [comment]
awesome thanks!

**Comment by akileez** [comment]
closing. and thanks to you as well.

**Comment by jonschlinkert** [comment]
@akileez we'll need to rename the command again since `mtree` already exists as well. it's freezes on my system. I'm going to go ahead and use `module-tree`

**Comment by akileez** [comment]
i was worried about that. (`/usr/sbin/mtree` on my system and the reason I originally thought of `dtree`)
depending on how your `$PATH` is configured this may lead to issues. 
`module-tree` is perfect.

**Comment by jonschlinkert** [comment]
:+1: great, thanks for the feedback
